# Name of the application
name: vox-md

# Regions where the service will be deployed
regions:
  - fra

services:
  - name: bot-service
    type: web
    ports:
      - 3000

    # Instance plan - upgraded to xsmall for more memory and stability
    instance:
      plan: xsmall

    # Environment variables
    env:
      - name: NODE_ENV
        value: production
      # Add Keep-Alive settings to prevent idle timeout
      - name: KEEP_ALIVE_INTERVAL
        value: "60000"

    # Build commands to install dependencies
    build:
      commands:
        - npm install

    # Run commands to start the service
    run:
      commands:
        - node index.js

    # Health check configuration
    health:
      path: /health
      interval: 30s
      timeout: 3s
      initial_delay: 20s
